"""Add trip_name, start_date, end_date and city_id to trips

Revision ID: 1e69a994022b
Revises: 2c6f4838a635
Create Date: 2025-05-29 21:41:10.700410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e69a994022b'
down_revision = '2c6f4838a635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_name', sa.String(length=255), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        # batch_op.drop_constraint(None, type_='foreignkey')  # ВИДАЛЕНО
        batch_op.drop_column('notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        # batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])  # ВИДАЛЕНО або додай ім'я якщо треба
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('trip_name')
    # ### end Alembic commands ###
