"""Add trip_name to Trip

Revision ID: 216f8c8113fa
Revises: 2f631c4c33fa
Create Date: 2025-05-31 22:13:03.380260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216f8c8113fa'
down_revision = '2f631c4c33fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('trip_name')

    # ### end Alembic commands ###
