"""Add City table and city_id to Trip

Revision ID: 2478e7024830
Revises: c3e8d6985498
Create Date: 2025-05-24 21:40:25.401281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2478e7024830'
down_revision = 'c3e8d6985498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_trip_city_id_city', 'city', ['city_id'], ['id'])
        batch_op.drop_column('latitude')
        batch_op.drop_column('location')
        batch_op.drop_column('longitude')
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('latitude', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint('fk_trip_city_id_city', type_='foreignkey')
        batch_op.drop_column('city_id')
    # ### end Alembic commands ###

