"""Remove budget_categories table and add total_budget column to trips

Revision ID: 5afc4b308d6c
Revises: 1e69a994022b
Create Date: 2025-05-31 20:29:11.723527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5afc4b308d6c'
down_revision = '1e69a994022b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget_categories')
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('total_budget', sa.Float(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_column('trip_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('total_budget')
        batch_op.drop_column('notes')

    op.create_table('budget_categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trip_id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=9), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
