"""add city tags

Revision ID: 665a9226c22f
Revises: a2a83cde62f1
Create Date: 2026-04-30 22:53:05.392845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665a9226c22f'
down_revision = 'a2a83cde62f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
