"""add user profile fields

Revision ID: 6d66c0719d0b
Revises: 665a9226c22f
Create Date: 2026-05-02 21:20:05.656966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d66c0719d0b'
down_revision = '665a9226c22f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('travel_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pace', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('budget', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('interests', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('preferred_tags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('preferred_tags')
        batch_op.drop_column('interests')
        batch_op.drop_column('budget')
        batch_op.drop_column('pace')
        batch_op.drop_column('travel_type')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
