"""add places table

Revision ID: 8593d2b994cd
Revises: 2779bb0e42f0
Create Date: 2026-04-20 16:16:34.679788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8593d2b994cd'
down_revision = '2779bb0e42f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('price_level',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('tags',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('tags',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('price_level',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    op.create_table('user_preferences',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('budget', sa.VARCHAR(length=20), nullable=True),
    sa.Column('days', sa.INTEGER(), nullable=True),
    sa.Column('travel_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('activity_level', sa.VARCHAR(length=50), nullable=True),
    sa.Column('region', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
