"""add places_loaded to cities

Revision ID: a2a83cde62f1
Revises: 8593d2b994cd
Create Date: 2026-04-25 14:47:27.106035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a83cde62f1'
down_revision = '8593d2b994cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('places_loaded', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_column('places_loaded')

    # ### end Alembic commands ###
